---
title: 'Comparison of GAMs and WRTDS for tidal waters'
author: "Marcus W. Beck, beck.marcus@epa.gov"
output:
  html_document:
    keep_md: yes
    self_contained: no
---

This repository contains materials for comparing generalized additive models (GAMs) and the recent adapation of Weighted Regression on Time, Discharge, and Season (WRTDS) for tidal waters.  Please see the [WRTDStidal](https://github.com/fawda123/wtreg_for_estuaries) page for an R package to implement WRTDS in tidal waters.

### Data files

`bestLE12.RData` combined dataset for best WRTDS and GAM for LE12, includes observed data, created in `create_final_mods.R`

`bestLE12_wrtds.RData` Optimal WRTDS model for LE12, created in `create_final_mods.R`
 
`bestLE12_gams.RData` Optimal GAM for LE12, created in `create_final_mods.R`
 
`bestTF16.RData` combined dataset for best WRTDS and GAM for TF16, includes observed data, created in `create_final_mods.R`
 
`bestTF16_wrtds.RData` Optimal WRTDS model for TF16, created in `create_final_mods.R`

`bestTF16_gams.RData` Optimal GAM for TF16, created in `create_final_mods.R`

`obs_dat.RData` Daily chlorophyll and discharge data that is used to create simulated datasets on monthly time steps, created in `sim_dat.R`.

`optimLE12_opt.RData` Results after running `winsrch_optim` for LE12, created in `get_optim.R`

`optimTF16_opt.RData` Results after running `winsrch_optim` for TF16, created in `get_optim.R`

`pax_chldata.RData` Chlorophyll data for Patuxent stations including bottom and surface.

`pax_clip.RData` SpatialPolygonsDataFrame of the Patuxent taken from a cut polygon of Chesapeake Bay.

`pax_data.RData` Processed water quality data for water quality stations in the Patuxent River Estuary, 1985 to 2014.  Created in dat_proc.Rnw.

`pax_meta.RData` Metadata for water quality stations in the Patuxent River Estuary, created in dat_proc.Rnw.
